// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plate.proto

// Protobuf Java Version: 3.25.2
package lab.plates.producer.proto;

public interface PlateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lab.plates.producer.proto.Plate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string plate = 1;</code>
   * @return The plate.
   */
  String getPlate();
  /**
   * <code>string plate = 1;</code>
   * @return The bytes for plate.
   */
  com.google.protobuf.ByteString
      getPlateBytes();
}
