// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plate.proto

// Protobuf Java Version: 3.25.2
package lab.plates.producer.proto;

public final class proto {
  private proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lab_plates_producer_proto_Plate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lab_plates_producer_proto_Plate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013plate.proto\022\031lab.plates.producer.proto" +
      "\"\026\n\005Plate\022\r\n\005plate\030\001 \001(\tB\021B\005protoP\001\242\002\005pr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lab_plates_producer_proto_Plate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lab_plates_producer_proto_Plate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lab_plates_producer_proto_Plate_descriptor,
        new String[] { "Plate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
